name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-web
      - run: flutter pub get
#       - run: flutter test
#       - run: flutter build web
      - run: flutter build apk
      
#       - name: copy web to vm
#         uses: garygrossgarten/github-action-scp@release
#         with:
#           local: ./build/web
#           remote: flutter_demo
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.SSH_USER }}
#           privateKey: ${{ secrets.SSH_KEY }}

#       - name: copy apk to vm
#         uses: garygrossgarten/github-action-scp@release
#         with:
#           local: ./build/app/outputs/flutter-apk/app-release.apk
#           remote: flutter_demo/app-release.apk
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.SSH_USER }}
#           privateKey: ${{ secrets.SSH_KEY }}
